In [4]:
import numpy as np


In [5]:
sarasas = [4, 3, 1, 5, 2,]
masyvas = np.array(sarasas)
print(masyvas)

[4 3 1 5 2]


In [8]:
x0 = [[1, 2, 3], [4, 5, 6], [7, 8, 9,]]
print(x0)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [9]:
x0matrix = np.array(x0)
print(x0matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print(np.arange(5, 200, 5))

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180
 185 190 195]


In [14]:
print(np.array(np.zeros(5)))

[0. 0. 0. 0. 0.]
